# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='love_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='study_num',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='love_num',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='work_year',
            field=models.IntegerField(verbose_name='工作年限'),
        ),
    ]
