# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_orginfo_course_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='flag',
            field=models.CharField(default='知名学校', max_length=10, verbose_name='学校品牌'),
        ),
    ]
