# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersprofile_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '修改'), ('changeemail', '更改邮箱')], default='register', max_length=12, verbose_name='验证类型'),
        ),
    ]
