# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='love_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='study_time',
            field=models.IntegerField(default=0, verbose_name='学习时长'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='stunum',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
        migrations.AlterField(
            model_name='videlinfo',
            name='stydy_time',
            field=models.IntegerField(default=0, verbose_name='视频时长'),
        ),
    ]
