# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180613_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='course/%y/%m', verbose_name='课程图片'),
        ),
    ]
