# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-22 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180621_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VidelInfo',
            new_name='VideoInfo',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='stydy_time',
            new_name='study_time',
        ),
    ]
